### ISSUE TITLE
pgoapi error

### ISSUE THREAD

**Issue by Varnsen** [modrzew/pokeminer#109]
Hey, when I attempt to run python worker.py, I get the following error:
```

Traceback (most recent call last):
  File "worker.py", line 11, in <module>
    from pgoapi import (
ImportError: No module named pgoapi
```

Running python web.py etc.
I get this error
```
Traceback (most recent call last):
  File "web.py", line 8, in <module>
    from flask_googlemaps import GoogleMaps
ImportError: No module named flask_googlemaps

```

It looks like the requirements aren't installing correctly. When I run pip install -r requirements.txt, this is the response I get:

```
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Downloading/unpacking coveralls==1.1 (from -r requirements.txt (line 8))
  Running setup.py egg_info for package coveralls

Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.11.10 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Downloading/unpacking sqlalchemy==1.0.14 (from -r requirements.txt (line 10))
  Running setup.py egg_info for package sqlalchemy

    warning: no files found matching '*.jpg' under directory 'doc'
    warning: no files found matching '*.mako' under directory 'doc'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'sa2to3.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@0811db23d639039f968a82e06c7aa15a0a5016b6#egg=pgoapi (from -r requirements.txt (line 11))
  Updating ./src/pgoapi clone (to 0811db23d639039f968a82e06c7aa15a0a5016b6)
  Could not find a tag or branch '0811db23d639039f968a82e06c7aa15a0a5016b6', assuming commit.
  Running setup.py egg_info for package pgoapi
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/x/Miner/src/pgoapi/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/x/Miner/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/x/Miner/src/pgoapi
```

Any idea how I can fix these errors?

**Comment by freakjam** [comment]
Fetch latest requirements.txt and run pip install again. The file was updated recently.

**Comment by Varnsen** [comment]
I just tried running it again, with the new requirements.txt (comparing the two - they look the same unless I'm getting the wrong one.)

Here's the pip.log that was generated. Sorry for the size!

```
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))

  skipping extra timezone
  skipping extra placefinder
Downloading/unpacking protobuf>=3.0.0a3 (from -r requirements.txt (line 2))

  Running setup.py egg_info for package protobuf

    running egg_info
    writing requirements to pip-egg-info/protobuf.egg-info/requires.txt
    writing pip-egg-info/protobuf.egg-info/PKG-INFO
    writing namespace_packages to pip-egg-info/protobuf.egg-info/namespace_packages.txt
    writing top-level names to pip-egg-info/protobuf.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/protobuf.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info/protobuf.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'google/protobuf/internal/import_test_package'

    warning: no previously-included files found matching 'google/protobuf/internal/*_pb2.py'

    warning: no previously-included files found matching 'google/protobuf/internal/*_test.py'

    warning: no previously-included files found matching 'google/protobuf/internal/*.proto'

    warning: no previously-included files found matching 'google/protobuf/internal/test_util.py'

    warning: no previously-included files matching '*_test.py' found under directory 'google'

    warning: no previously-included files matching '*_test.proto' found under directory 'google'

    warning: no previously-included files matching 'unittest*_pb2.py' found under directory 'google'

    warning: no previously-included files matching '*.dll' found anywhere in distribution

    warning: no previously-included files matching '*.pyc' found anywhere in distribution

    warning: no previously-included files matching '*.pyo' found anywhere in distribution

    warning: no previously-included files matching '*.so' found anywhere in distribution

    writing manifest file 'pip-egg-info/protobuf.egg-info/SOURCES.txt'
  Source in ./build/protobuf has version 3.0.0, which satisfies requirement protobuf>=3.0.0a3 (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))

  skipping extra security
  skipping extra security
  skipping extra security
  skipping extra socks
Downloading/unpacking flask-googlemaps==0.2.2 (from -r requirements.txt (line 4))

  Running setup.py egg_info for package flask-googlemaps

    running egg_info
    writing requirements to pip-egg-info/Flask_GoogleMaps.egg-info/requires.txt
    writing pip-egg-info/Flask_GoogleMaps.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/Flask_GoogleMaps.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/Flask_GoogleMaps.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info/Flask_GoogleMaps.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'example.py'

    warning: no files found matching 'example.html'

    writing manifest file 'pip-egg-info/Flask_GoogleMaps.egg-info/SOURCES.txt'
  Source in ./build/flask-googlemaps has version 0.2.2, which satisfies requirement flask-googlemaps==0.2.2 (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))

  skipping extra docs
  skipping extra docs
  skipping extra tests
  skipping extra tests
  skipping extra tests
  skipping extra tests
  skipping extra tests
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))

Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))

Downloading/unpacking coveralls==1.1 (from -r requirements.txt (line 8))

  Running setup.py egg_info for package coveralls

    running egg_info
    writing requirements to pip-egg-info/coveralls.egg-info/requires.txt
    writing pip-egg-info/coveralls.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/coveralls.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/coveralls.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/coveralls.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info/coveralls.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/coveralls.egg-info/SOURCES.txt'
  Source in ./build/coveralls has version 1.1, which satisfies requirement coveralls==1.1 (from -r requirements.txt (line 8))
  skipping extra yaml
Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.11.10 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))

Downloading/unpacking sqlalchemy==1.0.14 (from -r requirements.txt (line 10))

  Running setup.py egg_info for package sqlalchemy

    running egg_info
    writing pip-egg-info/SQLAlchemy.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/SQLAlchemy.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/SQLAlchemy.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info/SQLAlchemy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.jpg' under directory 'doc'

    warning: no files found matching '*.mako' under directory 'doc'

    warning: no files found matching 'distribute_setup.py'

    warning: no files found matching 'sa2to3.py'

    warning: no files found matching 'ez_setup.py'

    no previously-included directories found matching 'doc/build/output'

    writing manifest file 'pip-egg-info/SQLAlchemy.egg-info/SOURCES.txt'
  Source in ./build/sqlalchemy has version 1.0.14, which satisfies requirement sqlalchemy==1.0.14 (from -r requirements.txt (line 10))
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@0811db23d639039f968a82e06c7aa15a0a5016b6#egg=pgoapi (from -r requirements.txt (line 11))

  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git config remote.origin.url
  https://github.com/tejado/pgoapi.git
  Clone in ./src/pgoapi exists, and has correct URL (https://github.com/tejado/pgoapi.git)
  Updating ./src/pgoapi clone (to 0811db23d639039f968a82e06c7aa15a0a5016b6)

  Running command /usr/bin/git fetch -q
  Running command /usr/bin/git tag -l
  v1.1.0
  Running command /usr/bin/git rev-parse v1.1.0
  7ab17c59ebbaf6ec79e694fb3bd76438e1b45480
  Running command /usr/bin/git branch -r
    origin/HEAD -> origin/master
    origin/master
  Running command /usr/bin/git branch -l
  * (no branch)
    master
  Running command /usr/bin/git rev-parse origin/HEAD
  0811db23d639039f968a82e06c7aa15a0a5016b6
  Running command /usr/bin/git rev-parse origin/master
  0811db23d639039f968a82e06c7aa15a0a5016b6
  Running command /usr/bin/git rev-parse master
  0811db23d639039f968a82e06c7aa15a0a5016b6
  Could not find a tag or branch '0811db23d639039f968a82e06c7aa15a0a5016b6', assuming commit.

  Running command /usr/bin/git reset --hard -q 0811db23d639039f968a82e06c7aa15a0a5016b6
  Running setup.py egg_info for package pgoapi

    Traceback (most recent call last):

      File "<string>", line 14, in <module>

      File "/home/x/Miner/src/pgoapi/setup.py", line 9, in <module>

        install_reqs = parse_requirements(path_req, session=False)

    TypeError: parse_requirements() got an unexpected keyword argument 'session'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/x/Miner/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /home/x/Miner/src/pgoapi

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 964, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/x/Miner/src/pgoapi
```

**Comment by GaelicGamer** [comment]
This makes me think you might be on a different python version, what version of python are you using?

**Comment by Aiyubi** [comment]
@GaelicGamer you can see he has python 2.7 in the later filepathes

@Varnsen please try the following:
apt-get install python-dev python-setuptools

**Comment by Varnsen** [comment]
I just checked my Python version:

```
root@vps301597:/home/x/Miner# python -V
Python 2.7.3
```

We're looking at updating to 2.7.11 later on today, for PokeAlarm for our other map, and we can see if that fixes it.

Just ran the `apt-get install python-dev python-setuptools` command, judging by the response it did something. 
Running it a second time confirmed:
```
root@vps301597:/home/x/Miner# apt-get install python-dev python-setuptools
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-setuptools is already the newest version.
python-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
```

Then when I attempted to run worker and the webserver:

```
root@vps301597:/home/x/Miner# python worker.py
Traceback (most recent call last):
  File "worker.py", line 11, in <module>
    from pgoapi import (
ImportError: No module named pgoapi
root@vps301597:/home/x/Miner# python web.py --host IP --port PORT
Traceback (most recent call last):
  File "web.py", line 8, in <module>
    from flask_googlemaps import GoogleMaps
ImportError: No module named flask_googlemaps

```

Seems to be throwing the same error.

**Comment by modrzew** [comment]
Can you try using virtualenv? I highly advise to use it (and virtualenvwrapper, and pyenv) when interacting with any Python project.
