### ISSUE TITLE
Server busy or offline errors and workers dying

### ISSUE THREAD

**Issue by liquefry** [modrzew/pokeminer#114]
As some other issues have mentioned, workers seem to be dying off here.  My server suffers from a seperate error that noone else seems to have mentioned, and I suspect the two may be linked in some way.  I have dredged through my log files to try and diagnose.

Here's an extract of logs showing an error:

> [2016-08-03 09:04:39,696][ worker-36][    INFO][L 735] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
[2016-08-03 09:06:46,917][ worker-36][    INFO][L 184] Server seems to be busy or offline - try again!
[2016-08-03 09:06:46,918][ worker-36][    INFO][L 187] Cleanup of request!
[2016-08-03 09:06:46,918][ worker-36][   ERROR][L 131] A wild exception appeared!
Traceback (most recent call last):
  File "/var/hda/web-apps/pokeminer/pokeminer/worker.py", line 126, in run
    self.main()
  File "/var/hda/web-apps/pokeminer/pokeminer/worker.py", line 168, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: 'NoneType' object has no attribute '__getitem__'
[2016-08-03 09:06:46,918][ worker-25][   ERROR][L 131] A wild exception appeared!
Traceback (most recent call last):
  File "/var/hda/web-apps/pokeminer/pokeminer/worker.py", line 126, in run
    self.main()
  File "/var/hda/web-apps/pokeminer/pokeminer/worker.py", line 168, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: 'NoneType' object has no attribute '__getitem__'
[2016-08-03 09:06:46,918][ worker-12][   ERROR][L 131] A wild exception appeared!
Traceback (most recent call last):
  File "/var/hda/web-apps/pokeminer/pokeminer/worker.py", line 126, in run
    self.main()
  File "/var/hda/web-apps/pokeminer/pokeminer/worker.py", line 168, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: 'NoneType' object has no attribute '__getitem__'
[2016-08-03 09:06:54,924][ worker-36][    INFO][L 260] Worker (re)starting up!

From this point the worker normally restarts.  The workers are definitely all having trouble communicating with the server at the same time.  The "server busy" error lasts for between 4-8 seconds and all requests during this time are affected.  

Apologies for the rest of this post, I'm not a programmer but love to trawl data so I've taken a non-programming approach to analyse this!

The reason I think this may be related to the way that Pokeminer interacts with the Niantic servers is that the server offline error happens at regular intervals, without fail.  The intervals get longer as workers die off, suggesting that the connection is more stable with fewer workers making requests.

I've plotted the decay in the number of active workers over time for my server:
![image](https://cloud.githubusercontent.com/assets/4584269/17353351/356b026c-5982-11e6-842a-276798c964ac.png)

This shows a few things:
- the number of workers dying off decreases regularly over time
- the gap between server errors increases regularly over time (harder to see in the chart) - in my case, the first server error happened at 3m uptime, then after another 3, etc, slowly increasing to a gap of 7 minutes by the 26th error.  The additional chart from the same data below clearly shows the strong relationship between number of active workers and the "uptime" between server communication errors:

![image](https://cloud.githubusercontent.com/assets/4584269/17353498/8802934a-5983-11e6-9df4-b5a4d12960f3.png)

Both these factors seem to suggest that the program gets more stable with fewer workers.  This kind of makes sense as there will be less requests on the pokego servers.  But the regularity of both the workers dying off and the increasing gap between server communication errors suggests that it's not a random drop out problem, but a systematic issue that can hopefully be addressed?  My thoughts are that the pokego servers are perhaps overwhelmed by requests with lots of workers, so perhaps the gap between requests needs to be slightly higher.  I suppose it could also be a network issue, something to do with the number of simultaneous requests from the same network address.

Other info: I'm using the current build as of this morning (with hexagonal grid), running it on a fedora server with mariadb (mysql) database.  I have 100MB/s cable so internet speed shouldnt be the limitation, and plenty of free processor and memory capacity when pokeminer running.

**Comment by inexion** [comment]
Pretty sure this is why, https://www.reddit.com/r/pokemongodev/comments/4vuijn/psa_minimum_scan_refresh_now_10s/, where do we tweak refresh scan?

**Comment by plague180** [comment]
I was having the same issue, since I changed to 10 seconds I haven't had issues, however I don't think the one hour its been running since then is enough data, but before I was losing all workers in 15 min (ish)

**Comment by skarlath** [comment]
worker.py line 189

I set it to: time.sleep(random.uniform(10, 11))

**Comment by plague180** [comment]
I set it to: time.sleep(random.uniform(10, 12)) not that it really matters

**Comment by GaelicGamer** [comment]
I'm including an option in the config for the sleep timers, see pull #111

**Comment by liquefry** [comment]
Is that line the only one to change?  I have made the change to my worker.py (used 10,12) but still have workers dying off.

**Comment by GaelicGamer** [comment]
Hmmm, I'm using about 400 in one instance to test, not seeing it at that number, could I ask for a little more information on mariaDB, I'm not as familiar with it, just want to ensure that its nothing else because if it was Niantec or the amount of workers I would definitely been encountering it as I'm using a little over a thousand off of one machine atm.

**Comment by liquefry** [comment]
mariadb is basically an open source fork of mysql.  It works the same (and when using it, you use mysql commands).  See https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql.

**Comment by modrzew** [comment]
@liquefry I've been running 100 workers on v0.4.2 (which adds SCAN_DELAY) parameter and haven't seen that exception so far. Could you confirm?

**Comment by liquefry** [comment]
Thanks for the fix.  It seems to have reduced the problem but I'm still getting timeout errors at a lower frequency (every 5 mins or so), and losing a worker during each timeout.  I set the delay to 10s initially and then 15s with timeouts / workers dropping off as follows:
![image](https://cloud.githubusercontent.com/assets/4584269/17362045/ab6f97be-59b6-11e6-9cda-90ea4323097b.png)

The rise at 45 mins in is restarting worker.py with a 15s scan time.

The error I get after the timeout is the same as in the original post:

> [2016-08-03 20:05:03,365][ worker-30][    INFO][L 184] Server seems to be busy or offline - try again!
[2016-08-03 20:05:03,365][ worker-30][    INFO][L 187] Cleanup of request!
[2016-08-03 20:05:03,365][ worker-30][   ERROR][L 132] A wild exception appeared!
Traceback (most recent call last):
  File "/var/hda/web-apps/pokeminer/pokeminer/worker.py", line 127, in run
    self.main()
  File "/var/hda/web-apps/pokeminer/pokeminer/worker.py", line 169, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: 'NoneType' object has no attribute '__getitem__'
[2016-08-03 20:05:13,377][ worker-30][    INFO][L 263] Worker (re)starting up!

**Comment by liquefry** [comment]
Going to bed with server running, but preliminary results from reinstalling the git (without a fresh database) show the same problem still.  The decay is less pronounced though.
![image](https://cloud.githubusercontent.com/assets/4584269/17366009/4fe30d84-59cc-11e6-8513-071287c6af50.png)

For information, I'm checking active workers by the number of [info] lines attached to the worker in the log files, rather than the worker.py status.  The workers seem to die without any error logged, they just open a connection and then get lost somewhere.

**Comment by modrzew** [comment]
I think that 30s timeout from the most recent pgoapi will help with this issue. Also I've been adding fixes here and there in `coroutines` that should further improve the stability.

By the way, :+1: for charts!
