### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nern9** [modrzew/pokeminer#137]
![crash](https://cloud.githubusercontent.com/assets/7233855/17463840/54127ea8-5c8d-11e6-89e0-2d4cf39de6bb.PNG)

Not sure what is causing this issue.... anyone have an idea? it does it with every account that i put in there.

**Comment by Vashiru** [comment]
I've cloned a clean install, running into the same issue. Mac OS X.

**Comment by modrzew** [comment]
How long have you been running it for? Please run it for at least 5 minutes and then try again.

**Comment by nern9** [comment]
@modrzew its been on for about 20 minutes now, but nothing has appeared on the map, and it says exception next to all of the workers in the console

**Comment by Vashiru** [comment]
Yeah same, got some exceptions at first but they recovered. Others ended up as KILLED. Sightings table is empty. Running on the fort branch.

**Comment by nern9** [comment]
I was running on the master branch, but i switched over to fort and its still doing the same thing.

**Comment by Aiyubi** [comment]
to all the people reporting no pokemon seen: have you checked the worker.log ?
and did you get the .so file (or your operating systems variation)?

**Comment by nern9** [comment]
I think i might have forgotten to do that. where can i grab a copy of the .so file?

**Comment by nern9** [comment]
Looks like theres several different errors that pop up in the log
`Traceback (most recent call last):
  File "C:\Users\server\Desktop\pokeminer-master\worker.py", line 129, in run
    self.main()
  File "C:\Users\server\Desktop\pokeminer-master\worker.py", line 170, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: sequence index must be integer, not 'str'`

`Traceback (most recent call last):
  File "C:\Users\server\Desktop\pokeminer-master\worker.py", line 101, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "c:\users\server\desktop\pokeminer-master\src\pgoapi\pgoapi\pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "c:\users\server\desktop\pokeminer-master\src\pgoapi\pgoapi\pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "c:\users\server\desktop\pokeminer-master\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\server\desktop\pokeminer-master\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found`

**Comment by Vashiru** [comment]
@Aiyubi I compiled a libencrypt.so myself from another repo. After placing that into the folder I no longer got the error that I needed to install libencrypt.so so I'd assume its working correctly.

When I look at the worker.log there are no fatal errors, only the occasional exception which I mentioned earlier. That exception is:

```
[2016-08-07 20:31:52,792][ worker-45][   ERROR][L 134] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 129, in run
    self.main()
  File "worker.py", line 170, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: sequence index must be integer, not 'str'
```

**Comment by modrzew** [comment]
@Vashiru are you still not getting anything from the API? Did you investigate it further?

**Comment by gunawanputra** [comment]
@nern9 for Windows you should use encypt.dll, 32 or 64 bit depend on your Windows. you get error on get_map_object because U6 things, just like when API changed

**Comment by Vashiru** [comment]
@modrzew I'll give it another go tonight. Been busy the last few days so haven't tried again.

**Comment by Vashiru** [comment]
@modrzew Gave it another go. Failed at first, decided to download libencrypt from pogom rather than use the one I compiled, that seemed to have solved it. So albeit the other one not throwing any errors, it was breaking something somewhere down the drain. However when you have an empty database, the list index out of range error is still not resolved.
