### ISSUE TITLE
Sqlite error

### ISSUE THREAD

**Issue by Brewfasa** [modrzew/pokeminer#139]
I'm getting a error when i try to run the workers, it says something about missing the sighting table?
I'm currently running the bot with the encrypt32bit.dll file but i seem to get stuck at this point...

`[2016-08-07 19:27:52,465][  worker-2][    INFO][L 174] Login process completed
[2016-08-07 19:27:52,465][  worker-2][    INFO][L 159] Visiting point 0 (52.041639678027465 4.4705145809797715)
[2016-08-07 19:27:52,474][  worker-2][    INFO][L 278] Creating a new direct request...
[2016-08-07 19:27:52,475][  worker-2][    INFO][L 285] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
[2016-08-07 19:27:52,475][  worker-2][    INFO][L 212] Execution of RPC
[2016-08-07 19:27:52,477][  worker-2][    INFO][L 788] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
[2016-08-07 19:27:52,684][  worker-0][    INFO][L 254] Cleanup of request!
[2016-08-07 19:27:52,686][  worker-0][    INFO][L 186] Point processed, 0 Pokemons seen!
[2016-08-07 19:27:52,699][  worker-1][    INFO][L 254] Cleanup of request!
[2016-08-07` 19:27:52,704][  worker-1][   ERROR][L 134] A wild exception appeared!
Traceback (most recent call last):
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: sightings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "worker.py", line 129, in run
    self.main()
  File "worker.py", line 183, in main
    db.add_sighting(session, raw_pokemon)
  File "C:\Users\Danny\Desktop\blaaa\pokeminer-master\db.py", line 129, in add_sighting
    .filter(Sighting.lon == obj.lon) \
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\orm\query.py", line 2659, in first
    ret = list(self[0:1])
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\orm\query.py", line 2457, in __getitem__
    return list(res)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\orm\query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\orm\query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\util\compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: sightings [SQL: 'SELECT sightings.id AS sightings_id, sightings.pokemon_id AS sightings_pokemon_id, sightings.spawn_id AS sightings_spawn_id, sightings.expire_timestamp AS sightings_expire_timestamp, sightings.normalized_timestamp AS sightings_normalized_timestamp, sightings.lat AS sightings_lat, sightings.lon AS sightings_lon \nFROM sightings \nWHERE sightings.pokemon_id = ? AND sightings.spawn_id = ? AND sightings.expire_timestamp > ? AND sightings.expire_timestamp < ? AND sightings.lat = ? AND sightings.lon = ?\n LIMIT ? OFFSET ?'] [parameters: (129, '47c5c96caa1', 1470590987.6971655, 1470591007.6971655, 52.042842396026074, 4.464702821943068, 1, 0)]`

**After that it keeps spamming this:**
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\pool.py", line 290, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\default.py", line 426, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 20460 and this is thread id 12668
[2016-08-07 19:28:25,124][   Dummy-1][   ERROR][L 643] Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\default.py", line 420, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 13816 and this is thread id 12668
[2016-08-07 19:28:25,124][   Dummy-1][   ERROR][L 293] Exception closing connection <sqlite3.Connection object at 0x0528DE78>
Traceback (most recent call last):
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sqlalchemy\engine\default.py", line 420, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 13816 and this is thread id 12668`

**Comment by modrzew** [comment]
https://github.com/modrzew/pokeminer#setting-up
