### ISSUE TITLE
Worker exceptions

### ISSUE THREAD

**Issue by Zerotask** [modrzew/pokeminer#142]
I instantly get exceptions when starting worker.py.

> [2016-08-07 18:19:01,082][  worker-5][    INFO][L 140] PTC Access Token successfully retrieved.
[2016-08-07 18:19:01,082][  worker-5][    INFO][L 130] Starting RPC login sequence (app simulation)
[2016-08-07 18:19:01,083][  worker-5][    INFO][L 280] Creating a new request...
[2016-08-07 18:19:01,083][  worker-3][    INFO][L 140] PTC Access Token successfully retrieved.
[2016-08-07 18:19:01,084][  worker-5][    INFO][L 289] Adding 'GET_PLAYER' to RPC request
[2016-08-07 18:19:01,084][  worker-3][    INFO][L 130] Starting RPC login sequence (app simulation)
[2016-08-07 18:19:01,084][  worker-5][    INFO][L 289] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-07 18:19:01,084][  worker-3][    INFO][L 280] Creating a new request...
[2016-08-07 18:19:01,085][  worker-5][    INFO][L 289] Adding 'GET_INVENTORY' to RPC request
[2016-08-07 18:19:01,085][  worker-3][    INFO][L 289] Adding 'GET_PLAYER' to RPC request
[2016-08-07 18:19:01,085][  worker-5][    INFO][L 289] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-07 18:19:01,085][  worker-3][    INFO][L 289] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-07 18:19:01,085][  worker-5][    INFO][L 285] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-07 18:19:01,085][  worker-3][    INFO][L 289] Adding 'GET_INVENTORY' to RPC request
[2016-08-07 18:19:01,086][  worker-5][   ERROR][L 119] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 101, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "/bin/pokeminer/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./encrypt.so: invalid ELF header
[2016-08-07 18:19:01,086][  worker-3][    INFO][L 289] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-07 18:19:01,087][  worker-3][    INFO][L 285] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-07 18:19:01,087][  worker-3][   ERROR][L 119] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 101, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "/bin/pokeminer/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./encrypt.so: invalid ELF header
[2016-08-07 18:19:05,783][  worker-0][    INFO][L 265] Worker (re)starting up!
[2016-08-07 18:19:05,783][  worker-0][    INFO][L  50] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
[2016-08-07 18:19:05,785][  worker-0][    INFO][L  57] PTC User Login for: pogomapka01
[2016-08-07 18:19:05,787][  worker-0][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
[2016-08-07 18:19:06,099][  worker-0][   ERROR][L  88] Could not retrieve token: Account is not yet active, please redirect.
[2016-08-07 18:19:06,099][  worker-0][    INFO][L 130] Starting RPC login sequence (app simulation)
[2016-08-07 18:19:06,099][  worker-0][    INFO][L 280] Creating a new request...
[2016-08-07 18:19:06,100][  worker-0][    INFO][L 289] Adding 'GET_PLAYER' to RPC request
[2016-08-07 18:19:06,100][  worker-0][    INFO][L 289] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-07 18:19:06,100][  worker-0][    INFO][L 289] Adding 'GET_INVENTORY' to RPC request
[2016-08-07 18:19:06,100][  worker-0][    INFO][L 289] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-07 18:19:06,100][  worker-0][    INFO][L 285] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-07 18:19:06,100][  worker-0][    INFO][L 203] Not logged in
[2016-08-07 18:19:06,100][  worker-0][    INFO][L 143] Finished RPC login sequence (app simulation)
[2016-08-07 18:19:06,100][  worker-0][    INFO][L 174] Login process completed
[2016-08-07 18:19:06,101][  worker-0][    INFO][L 159] Visiting point 0 (49.0282557402 8.37493041811)
[2016-08-07 18:19:06,121][  worker-0][    INFO][L 278] Creating a new direct request...
[2016-08-07 18:19:06,121][  worker-0][    INFO][L 285] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
[2016-08-07 18:19:06,121][  worker-0][    INFO][L 203] Not logged in
[2016-08-07 18:19:06,121][  worker-0][   ERROR][L 134] A wild exception appeared!

**Comment by Aiyubi** [comment]
"invalid ELF header" <- thats the problem
you are using the wrong version of the encryption libary. Get the one fitting your operating system and architecture. See #135 for more hints

**Comment by Zerotask** [comment]
Thanks, that problem is solved now. Now I get the error:

> [2016-08-07 18:39:15,198][  worker-0][   ERROR][L 135] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 130, in run
    self.main()
  File "worker.py", line 167, in main
    cell_id=cell_ids
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/bin/pokeminer/src/pgoapi/pgoapi/rpc_api.py", line 141, in request
    raise ServerSideRequestThrottlingException("Request throttled by server... slow down man")
ServerSideRequestThrottlingException: Request throttled by server... slow down man

**Comment by Aiyubi** [comment]
Your scan delay should be a minimum of 10 seconds

**Comment by Zerotask** [comment]
Actually I didn't change the value. I tried it with 12 accounts now. it is working but 1-3 worker throw out a exception for few seconds, then it disappears.

> [2016-08-07 18:42:42,227][  worker-0][   ERROR][L 135] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 130, in run
    self.main()
  File "worker.py", line 172, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: sequence index must be integer, not 'str'

> Traceback (most recent call last):
  File "worker.py", line 130, in run
    self.main()
  File "worker.py", line 167, in main
    cell_id=cell_ids
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/bin/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/bin/pokeminer/src/pgoapi/pgoapi/rpc_api.py", line 141, in request
    raise ServerSideRequestThrottlingException("Request throttled by server... slow down man")
ServerSideRequestThrottlingException: Request throttled by server... slow down man

**Comment by YonderGod** [comment]
try a slower scan delay, like 11 or 12. 
*disclaimer: I'm not a dev, I don't know if this is the _correct_ way to solve this error, but it works.

**Comment by Vashiru** [comment]
@Zerotask The issue you describe in your last post is also mentioned in #137

**Comment by foozok** [comment]
Im getting this! how does one fix this?

Traceback (most recent call last):
  File "C:\Users\k\Desktop\pokeminer-0.4.3\worker.py", line 101, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "c:\users\k\desktop\pokeminer-0.4.3\src\pgoapi\pgoapi\pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "c:\users\k\desktop\pokeminer-0.4.3\src\pgoapi\pgoapi\pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "c:\users\k\desktop\pokeminer-0.4.3\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\k\desktop\pokeminer-0.4.3\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] module not found

**Comment by YonderGod** [comment]
@foozok Start your own thread, don't hijack someone else's with an unrelated issue.
