### ISSUE TITLE
Where to put encrypt64bit.dll?

### ISSUE THREAD

**Issue by MacxFlash** [modrzew/pokeminer#147]
Im getting the following error

Traceback (most recent call last):
  File "worker.py", line 347, in <module>
    spawn_workers(workers, status_bar=args.status_bar)
  File "worker.py", line 281, in spawn_workers
    start_worker(worker_no, points[worker_no])
  File "worker.py", line 269, in start_worker
    points=points
  File "worker.py", line 84, in __init__
    self.api.activate_signature(config.ENCRYPT_PATH)
  File "c:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

**Comment by YonderGod** [comment]
in the main folder, and edit your config to
`ENCRYPT_PATH = './encrypt64bit.dll'`

**Comment by MacxFlash** [comment]
Im still getting the same error.
config is
ENCRYPT_PATH = './encrypt64bit.dll'
and encrypt64bit.dll is located in main folder pokeminer-master

**Comment by modrzew** [comment]
Did you upgrade external dependencies? (`pip install --upgrade -r requirements.txt`)
