### ISSUE TITLE
Banned?

### ISSUE THREAD

**Issue by simonwahlstrom** [modrzew/pokeminer#148]
Started getting these exceptions:

`[2016-08-08 06:25:11,859][  worker-6][   ERROR][L 119] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 101, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "/home/ubuntu/workspace/newpoke/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/home/ubuntu/workspace/newpoke/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/home/ubuntu/workspace/newpoke/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/ubuntu/workspace/newpoke/pokeminer/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/ubuntu/workspace/newpoke/pokeminer/src/pgoapi/pgoapi/rpc_api.py", line 332, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")
ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...`

I have 20 workers running on a small area. Anyone experienced this before?

**Comment by Aiyubi** [comment]
guessing ptc accounts:
* are they new? if so you need to accept the tos
* did you activate them? they need to be activated within 48h after creation

**Comment by simonwahlstrom** [comment]
I created them on the 3rd of August. All of them have been activated. 

I can still log on to every account without any problem. No messages saying that they have been banned or so.

I have also tried using Google accounts but I have the same problem there.
