### ISSUE TITLE
WORKER EXCEPTION

### ISSUE THREAD

**Issue by photex12** [modrzew/pokeminer#156]
When running worker.py everything seems fine.
But after a few secconds this is what I see 
![image](https://cloud.githubusercontent.com/assets/20722379/17485712/bc2fd1b4-5d8e-11e6-8add-8c62c886c80c.png)

Whats going wrong?

**Comment by modrzew** [comment]
An exception happened!

Please check `worker.log` file.

**Comment by photex12** [comment]
@modrzew 
This is the error in the log

[2016-08-08 17:36:09,244][  worker-0][    INFO][L 265] Worker (re)starting up!
[2016-08-08 17:36:09,244][  worker-0][    INFO][L  50] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
[2016-08-08 17:36:09,244][  worker-0][    INFO][L  50] Google User Login for: thijsevers1985@gmail.com
[2016-08-08 17:36:09,244][  worker-0][    INFO][L 788] Starting new HTTPS connection (1): android.clients.google.com
[2016-08-08 17:36:09,668][  worker-0][    INFO][L  60] Google User Login successful.
[2016-08-08 17:36:09,668][  worker-0][    INFO][L  81] Request Google Access Token...
[2016-08-08 17:36:09,668][  worker-0][    INFO][L 788] Starting new HTTPS connection (1): android.clients.google.com
[2016-08-08 17:36:09,871][  worker-0][    INFO][L  92] Google Access Token successfully received.
[2016-08-08 17:36:09,871][  worker-0][    INFO][L 130] Starting RPC login sequence (app simulation)
[2016-08-08 17:36:09,871][  worker-0][    INFO][L 280] Creating a new request...
[2016-08-08 17:36:09,871][  worker-0][    INFO][L 289] Adding 'GET_PLAYER' to RPC request
[2016-08-08 17:36:09,871][  worker-0][    INFO][L 289] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-08 17:36:09,871][  worker-0][    INFO][L 289] Adding 'GET_INVENTORY' to RPC request
[2016-08-08 17:36:09,871][  worker-0][    INFO][L 289] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-08 17:36:09,871][  worker-0][    INFO][L 285] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-08 17:36:09,871][  worker-0][   ERROR][L 119] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 101, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "c:\users\iton\desktop\new folder (2)\src\pgoapi\pgoapi\pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "c:\users\iton\desktop\new folder (2)\src\pgoapi\pgoapi\pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "c:\users\iton\desktop\new folder (2)\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\iton\desktop\new folder (2)\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by Kieken72** [comment]
Can it be you are missing the Encrypt library? (dll)

**Comment by photex12** [comment]
@Kieken72 I'm afraid so.
Could you please help me as to how to get it?

**Comment by Kieken72** [comment]
@photex12 You can get the library for your system (Windows I assume) here -> https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom choose the dll matching your python install (32/64bit). 
Make sure your config file has this setting 
`ENCRYPT_PATH = './{libname}.{extension}' # external encryption library`
and place your library in the folder where the config.py is!

**Comment by photex12** [comment]
@Kieken72 THANK!!
After setting thing up I end up with the next error :(

LOG:
ConnectionError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x099B6630>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by modrzew** [comment]
It's something related to your OS and not pokeminer.
