### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by joeker94** [modrzew/pokeminer#160]
Running on MacOSx and am getting this error message when running worker.py

I've downloaded the libencrpyt.so file but am unsure what to do with it.

[2016-08-08 18:18:36,747][  worker-8][    INFO][L  60] Google User Login successful.
[2016-08-08 18:18:36,748][  worker-8][    INFO][L  81] Request Google Access Token...
[2016-08-08 18:18:36,761][  worker-8][    INFO][L 788] Starting new HTTPS connection (1): android.clients.google.com
[2016-08-08 18:18:36,972][  worker-8][    INFO][L  92] Google Access Token successfully received.
[2016-08-08 18:18:36,973][  worker-8][    INFO][L 130] Starting RPC login sequence (app simulation)
[2016-08-08 18:18:36,973][  worker-8][    INFO][L 280] Creating a new request...
[2016-08-08 18:18:36,973][  worker-8][    INFO][L 289] Adding 'GET_PLAYER' to RPC request
[2016-08-08 18:18:36,973][  worker-8][    INFO][L 289] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-08 18:18:36,973][  worker-8][    INFO][L 289] Adding 'GET_INVENTORY' to RPC request
[2016-08-08 18:18:36,973][  worker-8][    INFO][L 289] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-08 18:18:36,974][  worker-8][    INFO][L 285] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-08 18:18:36,974][  worker-8][   ERROR][L 119] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 101, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "/Users/xxxxxx/Desktop/pokeminer-master/src/pgoapi/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/Users/xxxxxx/Desktop/pokeminer-master/src/pgoapi/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/Users/xxxxxx/Desktop/pokeminer-master/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "/Users/xxxxxx/Desktop/pokeminer-master/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(./libencrypt.so, 6): image not found

**Comment by Aiyubi** [comment]
check the hints at #135
