### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Innenseide** [modrzew/pokeminer#163]
```
[2016-08-08 20:38:57,074][ worker-21][   ERROR][L 134] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 129, in run
    self.main()
  File "worker.py", line 166, in main
    cell_id=cell_ids
  File "/home/spezi/pokego/pokeminer-0.5.0/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/home/spezi/pokego/pokeminer-0.5.0/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/spezi/pokego/pokeminer-0.5.0/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/spezi/pokego/pokeminer-0.5.0/src/pgoapi/pgoapi/rpc_api.py", line 359, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/home/spezi/pokego/pokeminer-0.5.0/src/pgoapi/pgoapi/rpc_api.py", line 376, in _parse_sub_responses
    request_entry = subrequests_list[i]
IndexError: list index out of range
```

Getting this all the time, started like 30 minutes after updating to 0.5 including updates to the db, updating requirements and adapting config.py. Any ideas?

**Comment by Aiyubi** [comment]
as far as I can see this is an exception by the api: https://github.com/keyphact/pgoapi/issues/47

**Comment by Innenseide** [comment]
Thanks for referencing! Will have a look over there.

**Comment by pokemonracer** [comment]
[pgoapi/pull/59](https://github.com/keyphact/pgoapi/pull/59)

**Comment by modrzew** [comment]
pgoapi has been updated to keyphact/pgoapi@39ea20d31b770dd7bc83180d60283e171090e16d today in master's requirements.
