### ISSUE TITLE
Exception when opening /report

### ISSUE THREAD

**Issue by MSkjel** [modrzew/pokeminer#164]
Getting this exception when trying to access the report. It has to do with my GMaps Key or something(Same line in the config, at least)

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Servers\PokeMiner\web.py", line 198, in report_main
    google_maps_key=config.GOOGLE_MAPS_KEY,
  File "C:\Python27\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Servers\PokeMiner\templates\report.html", line 175, in top-level template code
    <a href="/report/{{ icon[0] }}"><img src="../static/larger-icons/{{ icon[0] }}.png" title="#{{ icon[0] }} {{ icon[1] }}"></a>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)

**Comment by Aiyubi** [comment]
you did not bother to look 2 issues below yours? #161
