### ISSUE TITLE
Data too long for column

### ISSUE THREAD

**Issue by skiniemini** [modrzew/pokeminer#166]
I noticed an issue with pokemon getting stored in the database and also the miniscual amount showing up on the map. I keep getting these errors:

```
Traceback (most recent call last):
  File "worker.py", line 129, in run
    self.main()
  File "worker.py", line 196, in main
    session.commit()
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\session.py", line 801, in commit
    self.transaction.commit()
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\session.py", line 392, in commit
    self._prepare_impl()
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\session.py", line 372, in _prepare_impl
    self.session.flush()
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush
    self._flush(objects)
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python27\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush
    flush_context.execute()
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    uow
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "C:\Python27\Lib\site-packages\sqlalchemy\orm\persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "C:\Python27\Lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\Lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\Lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\Lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Python27\Lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\Lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\Lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Python27\Lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python27\Lib\site-packages\MySQLdb\cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python27\Lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorvalue
DataError: (_mysql_exceptions.DataError) (1406, "Data too long for column 'lon' at row 1") [SQL: u'INSERT INTO sightings (pokemon_id, spawn_id, expire_timestamp, encounter_id, normalized_timestamp, lat, lon) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: (23, u'872bb09d483', 1470685374.54, '14576432015725599597', 1470685320, 33.44343602057562, -111.60584576518687)]

```

Can I fix this by just manually adjusting the structure of that column? (Raising the length/values)

Or is there something in a config file somewhere that needs to be changed?

**Comment by Aiyubi** [comment]
read the update notes: https://github.com/modrzew/pokeminer/releases/tag/v0.5.0

**Comment by skiniemini** [comment]
I already re-ran `db.Base.metadata.create_all(db.get_engine())`. That didn't work properly the first time so I setup a new database and ran the command again to create the tables. It created everything properly but I'm still getting that same error.

**Comment by kravock** [comment]
Lat and lon columns need to be size of 17 to accommodate for negative values
