### ISSUE TITLE
How to set Proxies ?

### ISSUE THREAD

**Issue by DavidSelem** [modrzew/pokeminer#195]

**Comment by Aiyubi** [comment]
see https://github.com/modrzew/pokeminer/pull/181

**Comment by DavidSelem** [comment]
Getting this 
Traceback (most recent call last):
  File "worker.py", line 103, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\pgoapi.py", line 173, in login
    response = self.app_simulation_login()
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\pgoapi.py", line 150, in app_simulation_login
    response = request.call()
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\pgoapi.py", line 217, in call
    request = RpcApi(self._auth_provider, self._proxy)
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\rpc_api.py", line 66, in __init__
    self._session.proxies = proxy_config
AttributeError: RpcApi instance has no attribute '_session'

**Comment by modrzew** [comment]
Did you run `pip install -r requirements.txt --upgrade`?

**Comment by DavidSelem** [comment]
Yes, I did it :(

**Comment by kton111** [comment]
i am not able to use proxy too. =[

**Comment by mugabemkomo** [comment]
Well I have the problem, I can enter a proxy, but it is not using the proxy.
Still connecting normally without proxy.

**Comment by freakjam** [comment]
You probably need this: https://github.com/keyphact/pgoapi/pull/77
