### ISSUE TITLE
A wild exception appeared!

### ISSUE THREAD

**Issue by wildpash** [modrzew/pokeminer#203]
Traceback (most recent call last):                                                                                       
  File "worker.py", line 128, in run                                                                                     
    self.main()                                                                                                          
  File "worker.py", line 170, in main                                                                                    
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})                                                  
TypeError: sequence index must be integer, not 'str'

**Comment by modrzew** [comment]
That's a known issue when servers have a hiccup. Worker should be restarted soon.
