### ISSUE TITLE
Exceptions 

### ISSUE THREAD

**Issue by ftheman2** [modrzew/pokeminer#208]
Getting this error:

[2016-08-11 19:51:12,750][  worker-0][   ERROR][L 125] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 103, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

Already ENCRYPT_PATH = './encrypt64bit.dll' and tryed the 32 version

my config.py file 
# coding: utf-8
from datetime import datetime

DB_ENGINE = 'sqlite:///db.sqlite'
ENCRYPT_PATH = 'encrypt64bit.dll'

MAP_START = (12.3456, 14.5)
MAP_END = (13.4567, 15.321)
GRID = (1, 1)
CYCLES_PER_WORKER = 3
SCAN_RADIUS = 70  # metres
SCAN_DELAY = 10  # seconds
ACCOUNTS = [
    ('xxxxx', 'xxxxx', 'ptc'),
]    
GOOGLE_MAPS_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
By the way pokemon go map works fine on my 64 bits system

Thank you

**Comment by leclaida** [comment]
try making the path ./encrypt64bit.dll

**Comment by ftheman2** [comment]
same output

**Comment by modrzew** [comment]
I assume that `./encrypt64bit.dll` did the trick.
