### ISSUE TITLE
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

### ISSUE THREAD

**Issue by JakeFlanagan** [modrzew/pokeminer#209]
[2016-08-11 22:10:05,303][worker-128][   ERROR][L 125] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 103, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 167, in login
    self.set_authentication(provider, username=username, password=password)
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 87, in set_authentication
    self._auth_provider.user_login(username, password)
  File "C:\Python27\lib\site-packages\pgoapi\auth_ptc.py", line 63, in user_login
    r = self._session.get(self.PTC_LOGIN_URL, headers=head)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Any ideas?

**Comment by Vashiru** [comment]
One worker and only one time? Probably just an accidental error during login, probably fixes itself on the retry.

**Comment by JakeFlanagan** [comment]
Sorry should have been more clear, i have  300 workers, every single one exceptions out.

**Comment by Vashiru** [comment]
First start or mid process? If it's first start you might want to double check if you're using the right libencrypt.dll. Make sure to match your python version so if you installed python x86 (32 bit) you'll need the 32 bit dll, if you installed python x86-64 (64 bit) you'll need 64 bit.

**Comment by JakeFlanagan** [comment]
First start, they'll all just fail with exception one after another within about 5 seconds from the first to last.

32 bit python using the 32 bit encrypt.dll. Full path specified in the config file too. worked previously, but now I'm getting nothing but exceptions.

**Comment by JakeFlanagan** [comment]
Okay its, somewhat working... the workers just never appear to pass 0% and only some aren't picking up anything on the map. Strange. I'll plod along with my project and see if anyone else has an issue like this later on.
