### ISSUE TITLE
Python 3.5 Error

### ISSUE THREAD

**Issue by DavidSelem** [modrzew/pokeminer#215]
Hello there, as @modrzew said, the future releases will only work with Py3.5, so I'm trying to make it work since now, but everytime it starts it has this error...
[2016-08-12 03:18:05,625][ worker-40][   ERROR][L 125] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 103, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\pgoapi.py", line 173, in login
    response = self.app_simulation_login()
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\pgoapi.py", line 150, in app_simulation_login
    response = request.call()
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\pgoapi.py", line 222, in call
    request.activate_signature(lib_path)
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\rpc_api.py", line 84, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python35\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python35\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 no es una aplicación Win32 válida

It doesn't have any problem while executing it with Py2.7

**Comment by Aiyubi** [comment]
did you install 64bit python or 32 bit? This could be your problem

**Comment by DavidSelem** [comment]
Yeah I solved by using the encrypt64.dll

A little weird because Py2.7 is also 64 bits and it was working fine even with encrypt32.dll
