### ISSUE TITLE
Maximum workers ~ 570

### ISSUE THREAD

**Issue by cryzies** [modrzew/pokeminer#22]
http://imgur.com/YsM79qg

**Comment by cryzies** [comment]
Increased to around 800 when I set the step to 1, BUT they don't restart after reaching 100%

**Comment by MonsterMMORPG** [comment]
SQLlite is very in efficient

did you move to another SQL?

**Comment by cryzies** [comment]
Do you have any recommendations? To be honest, I just want a city wide live map and don't need anything to do with saving pokemon sightings. Is there a way to remove the databasing but keep the live map?

**Comment by MonsterMMORPG** [comment]
i guess just keeping live map would require some strong code changes

as for SQL, i think even free microsoft SQL server can handle much better than sqllite

**Comment by modrzew** [comment]
SQLite is not very good choice for heavily-threaded application. Personally I'm using MySQL, and I'd recommend that or Postgres, as they are widely available.

**Comment by paperc07** [comment]
how do we go about using the above mentioned?

**Comment by modrzew** [comment]
First of all, you need to setup your database :wink: after that [change DB_ENGINE variable to point at your new database](http://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls).

**Comment by hallengreenn** [comment]
modrzew, can you help a bit?
Created the following table in my DB;

```
CREATE TABLE `sightings` (
  `id` INT NOT NULL DEFAULT 0,
  `pokemon_id` INT NULL DEFAULT 0,
  `spawn_id` VARCHAR(32) NULL DEFAULT NULL,
  `expire_timestamp` INT NULL DEFAULT 0,
  `normalized_timestamp` INT NULL DEFAULT 0,
  `lat` VARCHAR(16) NULL DEFAULT NULL,
  `lon` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id` ASC)
) DEFAULT CHARSET=utf8 ENGINE=InnoDB;
```

My config looks like this:
`DB_ENGINE = 'mysql+mysqldb://root@localhost/pokeminer'`

However there is error outputs all over the place, when running worker.py
`Exception in thread worker-111:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "worker.py", line 466, in run
    self.main(service, api_endpoint, access_token, profile_response)
  File "worker.py", line 493, in main
    db.add_sighting(session, spawn_id, pokemon)
  File "/home/administrator/pokeminer/db.py", line 64, in add_sighting
    .filter(Sighting.lon == obj.lon) \
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2760, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '0' for key 'PRIMARY'") [SQL: u'INSERT INTO sightings (pokemon_id, spawn_id, expire_timestamp, normalized_timestamp, lat, lon) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: (16, u'4652520f297', 1469547355.69537, 1469547240, 55.73620674994311, 12.534500901814114)]`

**Comment by 1n9i9c7om** [comment]
@hallengreenn Seems like you've an issue with duplicated primary keys:
`Duplicate entry '0' for key 'PRIMARY`

Do you have AUTO_INCREMENT enabled for your id column?

**Comment by hallengreenn** [comment]
1n9i9c7om, wow can't believe I missed that!
It is working now, with about 400 workers without any hickups.
Thank you for the assistance!

**Comment by Epion003** [comment]
@hallengreenn Sorry to bother I just got they program running for first time with only 6 workers. Was wondering if maybe you could tel me 1 how u made so many workers so fast took me some times just to make 6 making the gmail acct and ptc accts. But also I would like to set it up with a better DB like you guys did but not sure how to go about the whole process. Thank you for your time and any help

**Comment by 1n9i9c7om** [comment]
@Epion003 There are Account Creators available. 
There was one posted on reddit, but it got removed. That's the link to the reddit post: http://webcache.googleusercontent.com/search?q=cache:https://www.reddit.com/r/pokemongodev/comments/4uia6u/ptc_account_creator/&gws_rd=cr&ei=Q1iYV_uVAeOogAaZgYW4BA
It has a crash issue which I fixed by replacing the `break` in line 92 with time.sleep(5).

Check out this one if you rather want an alternative: https://github.com/coarse/ptc-account-maker

**Comment by hallengreenn** [comment]
@Epion003 , I used the program that @1n9i9c7om linked to. 
It works well with the time.sleep instead of break. 👍

**Comment by fmarmorini** [comment]
Thank you @1n9i9c7om

**Comment by Epion003** [comment]
Thank you @1n9i9c7om will check it out soon as I get home...

**Comment by paperc07** [comment]
@1n9i9c7om first off let me say thank you so much for this its amazing, actually to amazing, now that thousands of people are using the scripts and making free ptc accounts, is there anyway to make a google one, because in my experience ptc is down way more then google is, my google pogo accounts are usually always up

**Comment by 1n9i9c7om** [comment]
@paperc07 I don't know of any that works right now, especially because Google may be asking for phone verification after you created too many accounts - not sure tho.

**Comment by paperc07** [comment]
Ok thanks anyways and yeah they do, after so many.

**Comment by Epion003** [comment]
ok made it home and had a chance to Download few files... @hallengreenn @1n9i9c7om I got the acct file and saved it as a .py file. do i run that separately to generate a list of accts first or i use if combined fith the miner file? 2nd I DL MySQL server how do i go about setting it up so I dont mess anything up at the moment. Thank you again for any and all help....

**Comment by paperc07** [comment]
@modrzew which sql do we want the sql server?

**Comment by modrzew** [comment]
@paperc07 [anything supported by SQLAlchemy](http://docs.sqlalchemy.org/en/latest/core/engines.html).
