### ISSUE TITLE
Banned?

### ISSUE THREAD

**Issue by Maxxxel** [modrzew/pokeminer#228]
I get this on all accounts:

`Traceback (most recent call last):
  File "worker.py", line 136, in run
    self.main()
  File "worker.py", line 177, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: sequence index must be integer, not 'str'`

**Comment by Maxxxel** [comment]
read #203 i try my luck later to see if it is the server.

**Comment by modrzew** [comment]
The only thing I can do is catch that error and convert it into something more readable, as well as add more logging.

Which I just did, please check out 53d80dd.
