### ISSUE TITLE
NameError: global name 'pokemon_names' is not defined

### ISSUE THREAD

**Issue by BallTongue0** [modrzew/pokeminer#229]
I'm trying to combine the webhooks fork that @Brideau made with the discord fork @Devsome created and i think they are causing problems with each other.. When i start up my discordbot and the web.py i get this from the web.py

`Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Documents/Pokemap/pokeminer-master/web.py", line 68, in discord
    return json.dumps(get_pokeDiscord())
  File "/Users/user/Documents/Pokemap/pokeminer-master/web.py", line 159, in get_pokeDiscord
    name = pokemon_names[str(pokemon.pokemon_id)]
NameError: global name 'pokemon_names' is not defined`

And this from the Discord Bot
`Invalid response code: 500`

I'm not sure if i can post it here as a issue in the original pokeminer so please point me in the right direction!

**Comment by Devsome** [comment]
@BallTongue0 if you want I can pull the newest pokeminer tonight and check it with the Discord Bot.
But as the error log shows, that has nothing to do with the Discord Bot, because he is only pulling the json from web.py (function who created) the newest pokémon.
Maybe pokemon_names is not defined in the web.py file.

**Comment by BallTongue0** [comment]
@Devsome I found the problem... The pokemon_names was defined in CAPS so when changing the pokeDiscord name to POKEMON_NAMES the bot started working! Thanks anyways and awesome job with the bot!

**Comment by BallTongue0** [comment]
@devsome i do have a question tho, if i want to send the actual time it dissapears and not the time left is there a simple way to do that?
