### ISSUE TITLE
EXCEPTION across all workers

### ISSUE THREAD

**Issue by slxdegrees** [modrzew/pokeminer#234]
![exceptions](https://cloud.githubusercontent.com/assets/20662670/17664408/6cead9a8-6326-11e6-9369-3788ca9dd35c.png)

Did I miss a step or something? This seems to be a very new problem.

**Comment by DavidSelem** [comment]
What does your worker.log says?

**Comment by slxdegrees** [comment]
> [2016-08-15 20:46:28,545][MainThread][    INFO][L 384] ------------------------------
> [2016-08-15 20:46:28,545][MainThread][    INFO][L 385] Starting up!
> [2016-08-15 20:46:28,546][MainThread][    INFO][L 307] Worker (re)starting up!
> [2016-08-15 20:46:28,546][MainThread][    INFO][L  49] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
> [2016-08-15 20:46:28,546][MainThread][    INFO][L 307] Worker (re)starting up!
> [2016-08-15 20:46:28,546][MainThread][    INFO][L  49] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
> [2016-08-15 20:46:28,546][  worker-0][    INFO][L  57] PTC User Login for: tsukuru_44
> [2016-08-15 20:46:28,549][MainThread][    INFO][L 307] Worker (re)starting up!
> [2016-08-15 20:46:28,549][  worker-1][    INFO][L  57] PTC User Login for: tazaki_44
> [2016-08-15 20:46:28,549][MainThread][    INFO][L  49] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
> [2016-08-15 20:46:28,552][MainThread][    INFO][L 307] Worker (re)starting up!
> [2016-08-15 20:46:28,552][MainThread][    INFO][L  49] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
> [2016-08-15 20:46:28,552][  worker-2][    INFO][L  57] PTC User Login for: olivia_1311
> [2016-08-15 20:46:28,552][  worker-3][    INFO][L  57] PTC User Login for: rivvvvy_o
> [2016-08-15 20:46:28,568][  worker-2][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
> [2016-08-15 20:46:28,568][  worker-0][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
> [2016-08-15 20:46:28,568][  worker-1][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
> [2016-08-15 20:46:28,568][  worker-3][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
> [2016-08-15 20:46:30,232][  worker-0][    INFO][L  94] PTC User Login successful.
> [2016-08-15 20:46:30,232][  worker-0][    INFO][L 112] Request PTC Access Token...
> [2016-08-15 20:46:30,246][  worker-2][    INFO][L  94] PTC User Login successful.
> [2016-08-15 20:46:30,246][  worker-3][    INFO][L  94] PTC User Login successful.
> [2016-08-15 20:46:30,246][  worker-2][    INFO][L 112] Request PTC Access Token...
> [2016-08-15 20:46:30,246][  worker-3][    INFO][L 112] Request PTC Access Token...
> [2016-08-15 20:46:30,252][  worker-1][    INFO][L  94] PTC User Login successful.
> [2016-08-15 20:46:30,252][  worker-1][    INFO][L 112] Request PTC Access Token...
> [2016-08-15 20:46:30,585][  worker-0][    INFO][L 140] PTC Access Token successfully retrieved.
> [2016-08-15 20:46:30,585][  worker-0][    INFO][L 134] Starting RPC login sequence (app simulation)
> [2016-08-15 20:46:30,585][  worker-0][    INFO][L 286] Creating a new request...
> [2016-08-15 20:46:30,585][  worker-0][    INFO][L 295] Adding 'GET_PLAYER' to RPC request
> [2016-08-15 20:46:30,585][  worker-0][    INFO][L 295] Adding 'GET_HATCHED_EGGS' to RPC request
> [2016-08-15 20:46:30,585][  worker-0][    INFO][L 295] Adding 'GET_INVENTORY' to RPC request
> [2016-08-15 20:46:30,585][  worker-0][    INFO][L 295] Adding 'CHECK_AWARDED_BADGES' to RPC request
> [2016-08-15 20:46:30,585][  worker-0][    INFO][L 291] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
> [2016-08-15 20:46:30,585][  worker-0][   ERROR][L 125] A wild exception appeared!
> Traceback (most recent call last):
>   File "worker.py", line 103, in run
>     password=config.ACCOUNTS[self.worker_no][1],
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 168, in login
>     response = self.app_simulation_login()
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 145, in app_simulation_login
>     response = request.call()
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 216, in call
>     request.activate_signature(lib_path)
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\rpc_api.py", line 89, in activate_signature
>     self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
>   File "C:\Users\ratedR_slxdeg\AppData\Local\Python\lib\ctypes\__init__.py", line 440, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Users\ratedR_slxdeg\AppData\Local\Python\lib\ctypes\__init__.py", line 362, in __init__
>     self._handle = _dlopen(self._name, mode)
> WindowsError: [Error 193] %1 is not a valid Win32 application
> [2016-08-15 20:46:30,591][  worker-3][    INFO][L 140] PTC Access Token successfully retrieved.
> [2016-08-15 20:46:30,591][  worker-3][    INFO][L 134] Starting RPC login sequence (app simulation)
> [2016-08-15 20:46:30,591][  worker-3][    INFO][L 286] Creating a new request...
> [2016-08-15 20:46:30,591][  worker-3][    INFO][L 295] Adding 'GET_PLAYER' to RPC request
> [2016-08-15 20:46:30,591][  worker-3][    INFO][L 295] Adding 'GET_HATCHED_EGGS' to RPC request
> [2016-08-15 20:46:30,591][  worker-3][    INFO][L 295] Adding 'GET_INVENTORY' to RPC request
> [2016-08-15 20:46:30,591][  worker-3][    INFO][L 295] Adding 'CHECK_AWARDED_BADGES' to RPC request
> [2016-08-15 20:46:30,591][  worker-3][    INFO][L 291] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
> [2016-08-15 20:46:30,592][  worker-3][   ERROR][L 125] A wild exception appeared!
> Traceback (most recent call last):
>   File "worker.py", line 103, in run
>     password=config.ACCOUNTS[self.worker_no][1],
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 168, in login
>     response = self.app_simulation_login()
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 145, in app_simulation_login
>     response = request.call()
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 216, in call
>     request.activate_signature(lib_path)
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\rpc_api.py", line 89, in activate_signature
>     self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
>   File "C:\Users\ratedR_slxdeg\AppData\Local\Python\lib\ctypes\__init__.py", line 440, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Users\ratedR_slxdeg\AppData\Local\Python\lib\ctypes\__init__.py", line 362, in __init__
>     self._handle = _dlopen(self._name, mode)
> WindowsError: [Error 193] %1 is not a valid Win32 application
> [2016-08-15 20:46:30,598][  worker-1][    INFO][L 140] PTC Access Token successfully retrieved.
> [2016-08-15 20:46:30,599][  worker-1][    INFO][L 134] Starting RPC login sequence (app simulation)
> [2016-08-15 20:46:30,599][  worker-1][    INFO][L 286] Creating a new request...
> [2016-08-15 20:46:30,599][  worker-1][    INFO][L 295] Adding 'GET_PLAYER' to RPC request
> [2016-08-15 20:46:30,599][  worker-1][    INFO][L 295] Adding 'GET_HATCHED_EGGS' to RPC request
> [2016-08-15 20:46:30,601][  worker-1][    INFO][L 295] Adding 'GET_INVENTORY' to RPC request
> [2016-08-15 20:46:30,601][  worker-2][    INFO][L 140] PTC Access Token successfully retrieved.
> [2016-08-15 20:46:30,601][  worker-1][    INFO][L 295] Adding 'CHECK_AWARDED_BADGES' to RPC request
> [2016-08-15 20:46:30,601][  worker-2][    INFO][L 134] Starting RPC login sequence (app simulation)
> [2016-08-15 20:46:30,601][  worker-1][    INFO][L 291] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
> [2016-08-15 20:46:30,601][  worker-2][    INFO][L 286] Creating a new request...
> [2016-08-15 20:46:30,601][  worker-2][    INFO][L 295] Adding 'GET_PLAYER' to RPC request
> [2016-08-15 20:46:30,601][  worker-1][   ERROR][L 125] A wild exception appeared!
> Traceback (most recent call last):
>   File "worker.py", line 103, in run
>     password=config.ACCOUNTS[self.worker_no][1],
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 168, in login
>     response = self.app_simulation_login()
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 145, in app_simulation_login
>     response = request.call()
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 216, in call
>     request.activate_signature(lib_path)
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\rpc_api.py", line 89, in activate_signature
>     self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
>   File "C:\Users\ratedR_slxdeg\AppData\Local\Python\lib\ctypes\__init__.py", line 440, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Users\ratedR_slxdeg\AppData\Local\Python\lib\ctypes\__init__.py", line 362, in __init__
>     self._handle = _dlopen(self._name, mode)
> WindowsError: [Error 193] %1 is not a valid Win32 application
> [2016-08-15 20:46:30,601][  worker-2][    INFO][L 295] Adding 'GET_HATCHED_EGGS' to RPC request
> [2016-08-15 20:46:30,601][  worker-2][    INFO][L 295] Adding 'GET_INVENTORY' to RPC request
> [2016-08-15 20:46:30,602][  worker-2][    INFO][L 295] Adding 'CHECK_AWARDED_BADGES' to RPC request
> [2016-08-15 20:46:30,602][  worker-2][    INFO][L 291] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
> [2016-08-15 20:46:30,602][  worker-2][   ERROR][L 125] A wild exception appeared!
> Traceback (most recent call last):
>   File "worker.py", line 103, in run
>     password=config.ACCOUNTS[self.worker_no][1],
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 168, in login
>     response = self.app_simulation_login()
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 145, in app_simulation_login
>     response = request.call()
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 216, in call
>     request.activate_signature(lib_path)
>   File "c:\users\ratedr_slxdeg\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\rpc_api.py", line 89, in activate_signature
>     self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
>   File "C:\Users\ratedR_slxdeg\AppData\Local\Python\lib\ctypes\__init__.py", line 440, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Users\ratedR_slxdeg\AppData\Local\Python\lib\ctypes\__init__.py", line 362, in __init__
>     self._handle = _dlopen(self._name, mode)
> WindowsError: [Error 193] %1 is not a valid Win32 application
>

**Comment by slxdegrees** [comment]
```
[2016-08-15 20:46:28,545][MainThread][    INFO][L 384] ------------------------------
[2016-08-15 20:46:28,545][MainThread][    INFO][L 385] Starting up!
[2016-08-15 20:46:28,546][MainThread][    INFO][L 307] Worker (re)starting up!
[2016-08-15 20:46:28,546][MainThread][    INFO][L  49] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
[2016-08-15 20:46:28,546][MainThread][    INFO][L 307] Worker (re)starting up!
[2016-08-15 20:46:28,546][MainThread][    INFO][L  49] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
[2016-08-15 20:46:28,546][  worker-0][    INFO][L  57] PTC User Login for: tsukuru_44
[2016-08-15 20:46:28,549][MainThread][    INFO][L 307] Worker (re)starting up!
[2016-08-15 20:46:28,549][  worker-1][    INFO][L  57] PTC User Login for: tazaki_44
[2016-08-15 20:46:28,549][MainThread][    INFO][L  49] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
[2016-08-15 20:46:28,552][MainThread][    INFO][L 307] Worker (re)starting up!
[2016-08-15 20:46:28,552][MainThread][    INFO][L  49] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
[2016-08-15 20:46:28,552][  worker-2][    INFO][L  57] PTC User Login for: olivia_1311
[2016-08-15 20:46:28,552][  worker-3][    INFO][L  57] PTC User Login for: rivvvvy_o
[2016-08-15 20:46:28,568][  worker-2][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
[2016-08-15 20:46:28,568][  worker-0][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
[2016-08-15 20:46:28,568][  worker-1][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
[2016-08-15 20:46:28,568][  worker-3][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
[2016-08-15 20:46:30,232][  worker-0][    INFO][L  94] PTC User Login successful.
[2016-08-15 20:46:30,232][  worker-0][    INFO][L 112] Request PTC Access Token...
[2016-08-15 20:46:30,246][  worker-2][    INFO][L  94] PTC User Login successful.
[2016-08-15 20:46:30,246][  worker-3][    INFO][L  94] PTC User Login successful.
[2016-08-15 20:46:30,246][  worker-2][    INFO][L 112] Request PTC Access Token...
[2016-08-15 20:46:30,246][  worker-3][    INFO][L 112] Request PTC Access Token...
[2016-08-15 20:46:30,252][  worker-1][    INFO][L  94] PTC User Login successful.
[2016-08-15 20:46:30,252][  worker-1][    INFO][L 112] Request PTC Access Token...
[2016-08-15 20:46:30,585][  worker-0][    INFO][L 140] PTC Access Token successfully retrieved.
[2016-08-15 20:46:30,585][  worker-0][    INFO][L 134] Starting RPC login sequence (app simulation)
[2016-08-15 20:46:30,585][  worker-0][    INFO][L 286] Creating a new request...
[2016-08-15 20:46:30,585][  worker-0][    INFO][L 295] Adding 'GET_PLAYER' to RPC request
[2016-08-15 20:46:30,585][  worker-0][    INFO][L 295] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-15 20:46:30,585][  worker-0][    INFO][L 295] Adding 'GET_INVENTORY' to RPC request
[2016-08-15 20:46:30,585][  worker-0][    INFO][L 295] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-15 20:46:30,585][  worker-0][    INFO][L 291] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-15 20:46:30,585][  worker-0][   ERROR][L 125] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 103, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 168, in login
    response = self.app_simulation_login()
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 145, in app_simulation_login
    response = request.call()
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 216, in call
    request.activate_signature(lib_path)
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\rpc_api.py", line 89, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Users\User\AppData\Local\Python\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\User\AppData\Local\Python\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
[2016-08-15 20:46:30,591][  worker-3][    INFO][L 140] PTC Access Token successfully retrieved.
[2016-08-15 20:46:30,591][  worker-3][    INFO][L 134] Starting RPC login sequence (app simulation)
[2016-08-15 20:46:30,591][  worker-3][    INFO][L 286] Creating a new request...
[2016-08-15 20:46:30,591][  worker-3][    INFO][L 295] Adding 'GET_PLAYER' to RPC request
[2016-08-15 20:46:30,591][  worker-3][    INFO][L 295] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-15 20:46:30,591][  worker-3][    INFO][L 295] Adding 'GET_INVENTORY' to RPC request
[2016-08-15 20:46:30,591][  worker-3][    INFO][L 295] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-15 20:46:30,591][  worker-3][    INFO][L 291] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-15 20:46:30,592][  worker-3][   ERROR][L 125] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 103, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 168, in login
    response = self.app_simulation_login()
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 145, in app_simulation_login
    response = request.call()
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 216, in call
    request.activate_signature(lib_path)
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\rpc_api.py", line 89, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Users\User\AppData\Local\Python\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\User\AppData\Local\Python\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
[2016-08-15 20:46:30,598][  worker-1][    INFO][L 140] PTC Access Token successfully retrieved.
[2016-08-15 20:46:30,599][  worker-1][    INFO][L 134] Starting RPC login sequence (app simulation)
[2016-08-15 20:46:30,599][  worker-1][    INFO][L 286] Creating a new request...
[2016-08-15 20:46:30,599][  worker-1][    INFO][L 295] Adding 'GET_PLAYER' to RPC request
[2016-08-15 20:46:30,599][  worker-1][    INFO][L 295] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-15 20:46:30,601][  worker-1][    INFO][L 295] Adding 'GET_INVENTORY' to RPC request
[2016-08-15 20:46:30,601][  worker-2][    INFO][L 140] PTC Access Token successfully retrieved.
[2016-08-15 20:46:30,601][  worker-1][    INFO][L 295] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-15 20:46:30,601][  worker-2][    INFO][L 134] Starting RPC login sequence (app simulation)
[2016-08-15 20:46:30,601][  worker-1][    INFO][L 291] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-15 20:46:30,601][  worker-2][    INFO][L 286] Creating a new request...
[2016-08-15 20:46:30,601][  worker-2][    INFO][L 295] Adding 'GET_PLAYER' to RPC request
[2016-08-15 20:46:30,601][  worker-1][   ERROR][L 125] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 103, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 168, in login
    response = self.app_simulation_login()
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 145, in app_simulation_login
    response = request.call()
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 216, in call
    request.activate_signature(lib_path)
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\rpc_api.py", line 89, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Users\User\AppData\Local\Python\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\User\AppData\Local\Python\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
[2016-08-15 20:46:30,601][  worker-2][    INFO][L 295] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-15 20:46:30,601][  worker-2][    INFO][L 295] Adding 'GET_INVENTORY' to RPC request
[2016-08-15 20:46:30,602][  worker-2][    INFO][L 295] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-15 20:46:30,602][  worker-2][    INFO][L 291] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-15 20:46:30,602][  worker-2][   ERROR][L 125] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 103, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 168, in login
    response = self.app_simulation_login()
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 145, in app_simulation_login
    response = request.call()
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\pgoapi.py", line 216, in call
    request.activate_signature(lib_path)
  File "c:\users\User\desktop\pokemon go hax & tools\pokeminer-0.5.3\src\pgoapi\pgoapi\rpc_api.py", line 89, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Users\User\AppData\Local\Python\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\User\AppData\Local\Python\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

```

**Comment by Aiyubi** [comment]
this looks you referenced the encryption libary wrong in your config.

**Comment by slxdegrees** [comment]
Hmm should I leave it as it is in the example config file?
