### ISSUE TITLE
What to remove if only database is needed?

### ISSUE THREAD

**Issue by and7ey** [modrzew/pokeminer#247]
I don't need to display pokemons on the map and to generate report (only database file should be generated). What can I safely remove from the package?

(the script will be running on the NAS, pip is not there, so I will have to download and install all packages manually - would like to understand what I can skin)

**Comment by modrzew** [comment]
Just don't run `web.py`. All frontend requirements are pretty lightweight compared to backend ones. No need to remove anything I think.

**Comment by Aiyubi** [comment]
and if you can install modules - why not just install pip? Its just another module

**Comment by and7ey** [comment]
I will manually download, unpack and copy modules to pokeminer folder (it is not installation :)

**Comment by modrzew** [comment]
But why would you do that? Why can't you run this in virtualenv? Moreover, Python from 2.7 onwards has `ensurepip` module which just installs pip. You can then use it to install all requirements.

**Comment by and7ey** [comment]
Can not install pip there. It says:
`OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pip-8.1.2.dist-info'`
and there is no sudo - `sudo: not found`.

(`python -m ensurepip` returns the same error)

**Comment by and7ey** [comment]
I managed to install pip, but can not install xxhash - 

```
Collecting xxhash (from -r requirements.txt (line 7))
  Using cached xxhash-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lB6raN/xxhash/setup.py", line 58, in <module>
        'Programming Language :: Python :: Implementation :: CPython',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (nose 1.1.2 (/usr/local/lib/python2.7/site-packages), Requirement.parse('nose>=1.3.0'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lB6raN/xxhash/
```

Is it required for the core functionality?

**Comment by YonderGod** [comment]
I had troubles with xxhash, I had to install manually.

**Comment by Aiyubi** [comment]
Also you should be looking into Python 3.5 since it is needed for future pokeminer
