### ISSUE TITLE
TypeError: 'float' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by jorgejung** [modrzew/pokeminer#31]
How I can fix this? Thank you!

```
E:\Pokemon\pokeminer-0.3.1>python worker.py
Traceback (most recent call last):
  File "worker.py", line 658, in <module>
    spawn_workers(workers, status_bar=args.status_bar)
  File "worker.py", line 612, in spawn_workers
    points = utils.get_points_per_worker()
  File "E:\Pokemon\pokeminer-0.3.1\utils.py", line 46, in get_points_per_worker
    abs(config.MAP_START[0] - config.MAP_END[0]) / lat_gain
TypeError: 'float' object has no attribute '__getitem__'

E:\Pokemon\pokeminer-0.3.1>
```

**Comment by modrzew** [comment]
What's your `config.py`, specifically, the `MAP_START` and `MAP_END` variables?

**Comment by jorgejung** [comment]
Thank you!, I was placing only the lat on the config, fixed now!
