### ISSUE TITLE
error in log causing map to not be updated

### ISSUE THREAD

**Issue by techdough** [modrzew/pokeminer#44]
I see this every so often. I am not 100% sure but usually when I see this error I also see one of the workers at p0, 0%. whenever this error occurs I believe the map does not update with pokemons for that specific map node this worker is assigned to.

also it seems the more workers you have the more often this shows up. when i have 10 i never see it. when i have 20 i see it sometimes, when i have 30 i see it a fair bit.

looks very much like a thread safety issue.

[2016-07-26 08:00:24,808][ worker-14][   ERROR][L 643] Exception during reset or similar 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 420, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4064 and this is thread id 11596
[2016-07-26 08:00:24,809][ worker-14][   ERROR][L 293] Exception closing connection <sqlite3.Connection object at 0x00000000080C4770>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 290, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 426, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4064 and this is thread id 11596

**Comment by modrzew** [comment]
The quick workaround would be switching to MySQL (or other database engine).

**Comment by modrzew** [comment]
I'm in the middle of writing a better solution for database handling - no longer will each worker talk to database, but do it via different entity instead, capable of working on database more efficiently. Thus, closing.
