### ISSUE TITLE
DB error

### ISSUE THREAD

**Issue by Mila432** [modrzew/pokeminer#53]
Another db error:

```
[   ERROR][L 643] Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140415700924160 and this is thread id 140418410850048
[2016-07-27 20:19:24,246][ worker-45][   ERROR][L 293] Exception closing connection <sqlite3.Connection object at 0x7fb5f45173d0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 290, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 426, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140415700924160 and this is thread id 140418410850048

```

**Comment by Aiyubi** [comment]
duplicate of #44

**Comment by Mila432** [comment]
fixed
