### ISSUE TITLE
SQLite thread error

### ISSUE THREAD

**Issue by skiniemini** [modrzew/pokeminer#56]
Keep getting these errors
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 420, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 1680 and this is thread id 5048
[2016-07-27 14:50:08,665][ worker-30][   ERROR][L 293] Exception closing connection <sqlite3.Connection object at 0x00000000044263D0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 290, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 426, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 1680 and this is thread id 5048
```

**Comment by techdough** [comment]
dupe #44
