### ISSUE TITLE
Multiple exceptions since I updated to the new version

### ISSUE THREAD

**Issue by Shentang** [modrzew/pokeminer#86]
I updated today, and I'm getting something like this:
```

[2016-07-31 13:55:44,846][ worker-69][   ERROR][L 117] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 99, in run
    password=config.ACCOUNTS[self.worker_no][1],
  File "/root/pokeminer/src/pgoapi/pgoapi/pgoapi.py", line 110, in login
    if not self._auth_provider.login(username, password):
  File "/root/pokeminer/src/pgoapi/pgoapi/auth_ptc.py", line 54, in login
    r = self._session.get(self.PTC_LOGIN_URL, headers=head)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno bad ca_certs: '/usr/local/lib/python2.7/dist-packages/certifi/cacert.pem'] [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

**Comment by Aiyubi** [comment]
got the same error on one of my systems

**Comment by GaelicGamer** [comment]
How many workers are each of you using?

**Comment by Axi0m-S** [comment]
Same problem here. Using 100~ workers. It only happens after some time. I think maybe some sessions are not well closed. (Maybe it misses timeout somewhere)

**Comment by modrzew** [comment]
Could this be solved by https://github.com/keyphact/pgoapi/commit/e4895940c4b4571dc09136ef8dc3d4708f4be9fc?

**Comment by Axi0m-S** [comment]
No I still had the issue after this. I'm not sure what is causing this. It looks better since they updated the session reuse stuff (not sure)
