### ISSUE TITLE
exception in thread-wokrer-0

### ISSUE THREAD

**Issue by xBorsti** [modrzew/pokeminer#9]
Hi, i get an exception in thread-worker-0:

```
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "worker.py", line 464, in work
    main(worker_no, service, api_endpoint, access_token, profile_response)
  File "worker.py", line 515, in main
    db.add_sighting(session, spawn_id, pokemon)
  File "C:\Test\pokeminer-master\db.py", line 57, in add_sighting
    .filter(Sighting.lon == obj.lon) \
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2659, in first
    ret = list(self[0:1])
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2457, in __getitem__
    return list(res)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: sightings [SQL: u'SELECT sightings.id AS sightings_id, sightings.pokemon_id AS sightings_pokemon_id, sightings.spawn_id AS sightings_spawn_id, sightings.expire_timestamp AS sightings_expire_timestamp, sightings.normalized_timestamp AS sightings_normalized_timestamp, sightings.lat AS sightings_lat, sightings.lon AS sightings_lon \nFROM sightings \nWHERE sightings.pokemon_id = ? AND sightings.spawn_id = ? AND sightings.expire_timestamp > ? AND sightings.expire_timestamp < ? AND sightings.lat = ? AND sightings.lon = ?\n LIMIT ? OFFSET ?'] [parameters: (50, u'47a85a67119', 1469197967.212, 1469197987.212, 52.44838598708512, 13.298878686490871, 1, 0)]
```

did i forget to setup something?

**Comment by clearminds** [comment]
Yes you did - you forgot to create the tables - check the bottom of the README for instructions

**Comment by xBorsti** [comment]
yeah i got a problem with running a python REPL, any help maybe?

**Comment by xBorsti** [comment]
i got it running now, thanks
