### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'timetuple'

### ISSUE THREAD

**Issue by theresthatguy** [modrzew/pokeminer#92]
I am getting this error why trying to view any reports.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/theresthatguy/Pokemon/pokeminer-lite/web.py", line 190, in report_main
    top_pokemon = db.get_top_pokemon(session)
  File "/home/theresthatguy/Pokemon/pokeminer-lite/db.py", line 205, in get_top_pokemon
    '''.format(order=order, count=count, report_since=get_since_query_part()))
  File "/home/theresthatguy/Pokemon/pokeminer-lite/db.py", line 106, in get_since_query_part
    since=get_since(),
  File "/home/theresthatguy/Pokemon/pokeminer-lite/db.py", line 98, in get_since
    return time.mktime(config.REPORT_SINCE.timetuple())
AttributeError: 'tuple' object has no attribute 'timetuple'
```

**Comment by VirtualSatai** [comment]
Does your `config.py` contain a valid `REPORT_SINCE` ? 
I.e:
```
from datetime import datetime
#[...]
REPORT_SINCE = datetime(2016, 7, 29)
#[...]
```

**Comment by jane0815** [comment]
Same problem here. 

When i use: "REPORT_SINCE = datetime(2016, 7, 29)" i get the error that datetime is unknown. When i use "REPORT_SINCE = (2016, 7, 29)" web.py will start but i still get "AttributeError: 'tuple' object has no attribute 'timetuple'"

**Comment by VirtualSatai** [comment]
@jane0815 You should also insert `from datetime import datetime` to the top of `config.py`. 

The `REPORT_SINCE = (2016, 7, 29)` isn't a timetuple since it's just a tuple of ints. 

If you keep having issues, then I'd advice you to copy the `config.py.example` and start over.

**Comment by theresthatguy** [comment]
@VirtualSatai Thank you. I originally used and modified the example config that had 
`REPORT_SINCE = datetime(2016, 7, 29)`
Which gave me an error, so I removed the 'datetime' from the variable and the workers started. I was unaware of `from datetime import datetime` needed to be at the top since I didn't see it mentioned anywhere till here. Thank you for your replies. Everything is in working order again.
